services:
  pg:
    image: postgres:16.3-bullseye
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "conversia"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_conversia:/var/lib/postgresql/data
volumes:
  postgres_data_conversia: